//
// gRPC Service Definition for Mock Cat Service
// Following Nutanix patterns from ntnx-api-guru

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: cat_service.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListCatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Orderby       string                 `protobuf:"bytes,4,opt,name=orderby,proto3" json:"orderby,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCatsRequest) Reset() {
	*x = ListCatsRequest{}
	mi := &file_cat_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatsRequest) ProtoMessage() {}

func (x *ListCatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatsRequest.ProtoReflect.Descriptor instead.
func (*ListCatsRequest) Descriptor() ([]byte, []int) {
	return file_cat_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListCatsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCatsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCatsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListCatsRequest) GetOrderby() string {
	if x != nil {
		return x.Orderby
	}
	return ""
}

type ListCatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cats          []*Cat                 `protobuf:"bytes,1,rep,name=cats,proto3" json:"cats,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCatsResponse) Reset() {
	*x = ListCatsResponse{}
	mi := &file_cat_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatsResponse) ProtoMessage() {}

func (x *ListCatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cat_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatsResponse.ProtoReflect.Descriptor instead.
func (*ListCatsResponse) Descriptor() ([]byte, []int) {
	return file_cat_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListCatsResponse) GetCats() []*Cat {
	if x != nil {
		return x.Cats
	}
	return nil
}

func (x *ListCatsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListCatsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCatsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetCatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CatId         int32                  `protobuf:"varint,1,opt,name=cat_id,json=catId,proto3" json:"cat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatRequest) Reset() {
	*x = GetCatRequest{}
	mi := &file_cat_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatRequest) ProtoMessage() {}

func (x *GetCatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatRequest.ProtoReflect.Descriptor instead.
func (*GetCatRequest) Descriptor() ([]byte, []int) {
	return file_cat_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetCatRequest) GetCatId() int32 {
	if x != nil {
		return x.CatId
	}
	return 0
}

type GetCatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cat           *Cat                   `protobuf:"bytes,1,opt,name=cat,proto3" json:"cat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatResponse) Reset() {
	*x = GetCatResponse{}
	mi := &file_cat_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatResponse) ProtoMessage() {}

func (x *GetCatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cat_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatResponse.ProtoReflect.Descriptor instead.
func (*GetCatResponse) Descriptor() ([]byte, []int) {
	return file_cat_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetCatResponse) GetCat() *Cat {
	if x != nil {
		return x.Cat
	}
	return nil
}

type CreateCatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cat           *Cat                   `protobuf:"bytes,1,opt,name=cat,proto3" json:"cat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCatRequest) Reset() {
	*x = CreateCatRequest{}
	mi := &file_cat_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCatRequest) ProtoMessage() {}

func (x *CreateCatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCatRequest.ProtoReflect.Descriptor instead.
func (*CreateCatRequest) Descriptor() ([]byte, []int) {
	return file_cat_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCatRequest) GetCat() *Cat {
	if x != nil {
		return x.Cat
	}
	return nil
}

type CreateCatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cat           *Cat                   `protobuf:"bytes,1,opt,name=cat,proto3" json:"cat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCatResponse) Reset() {
	*x = CreateCatResponse{}
	mi := &file_cat_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCatResponse) ProtoMessage() {}

func (x *CreateCatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cat_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCatResponse.ProtoReflect.Descriptor instead.
func (*CreateCatResponse) Descriptor() ([]byte, []int) {
	return file_cat_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCatResponse) GetCat() *Cat {
	if x != nil {
		return x.Cat
	}
	return nil
}

type UpdateCatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CatId         int32                  `protobuf:"varint,1,opt,name=cat_id,json=catId,proto3" json:"cat_id,omitempty"`
	Cat           *Cat                   `protobuf:"bytes,2,opt,name=cat,proto3" json:"cat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCatRequest) Reset() {
	*x = UpdateCatRequest{}
	mi := &file_cat_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCatRequest) ProtoMessage() {}

func (x *UpdateCatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCatRequest.ProtoReflect.Descriptor instead.
func (*UpdateCatRequest) Descriptor() ([]byte, []int) {
	return file_cat_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCatRequest) GetCatId() int32 {
	if x != nil {
		return x.CatId
	}
	return 0
}

func (x *UpdateCatRequest) GetCat() *Cat {
	if x != nil {
		return x.Cat
	}
	return nil
}

type UpdateCatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cat           *Cat                   `protobuf:"bytes,1,opt,name=cat,proto3" json:"cat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCatResponse) Reset() {
	*x = UpdateCatResponse{}
	mi := &file_cat_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCatResponse) ProtoMessage() {}

func (x *UpdateCatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cat_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCatResponse.ProtoReflect.Descriptor instead.
func (*UpdateCatResponse) Descriptor() ([]byte, []int) {
	return file_cat_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCatResponse) GetCat() *Cat {
	if x != nil {
		return x.Cat
	}
	return nil
}

type DeleteCatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CatId         int32                  `protobuf:"varint,1,opt,name=cat_id,json=catId,proto3" json:"cat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCatRequest) Reset() {
	*x = DeleteCatRequest{}
	mi := &file_cat_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCatRequest) ProtoMessage() {}

func (x *DeleteCatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCatRequest.ProtoReflect.Descriptor instead.
func (*DeleteCatRequest) Descriptor() ([]byte, []int) {
	return file_cat_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteCatRequest) GetCatId() int32 {
	if x != nil {
		return x.CatId
	}
	return 0
}

type DeleteCatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCatResponse) Reset() {
	*x = DeleteCatResponse{}
	mi := &file_cat_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCatResponse) ProtoMessage() {}

func (x *DeleteCatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cat_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCatResponse.ProtoReflect.Descriptor instead.
func (*DeleteCatResponse) Descriptor() ([]byte, []int) {
	return file_cat_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteCatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetCatAsyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CatId         int32                  `protobuf:"varint,1,opt,name=cat_id,json=catId,proto3" json:"cat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatAsyncRequest) Reset() {
	*x = GetCatAsyncRequest{}
	mi := &file_cat_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatAsyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatAsyncRequest) ProtoMessage() {}

func (x *GetCatAsyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatAsyncRequest.ProtoReflect.Descriptor instead.
func (*GetCatAsyncRequest) Descriptor() ([]byte, []int) {
	return file_cat_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetCatAsyncRequest) GetCatId() int32 {
	if x != nil {
		return x.CatId
	}
	return 0
}

type GetCatAsyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	PollUrl       string                 `protobuf:"bytes,2,opt,name=poll_url,json=pollUrl,proto3" json:"poll_url,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatAsyncResponse) Reset() {
	*x = GetCatAsyncResponse{}
	mi := &file_cat_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatAsyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatAsyncResponse) ProtoMessage() {}

func (x *GetCatAsyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cat_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatAsyncResponse.ProtoReflect.Descriptor instead.
func (*GetCatAsyncResponse) Descriptor() ([]byte, []int) {
	return file_cat_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetCatAsyncResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetCatAsyncResponse) GetPollUrl() string {
	if x != nil {
		return x.PollUrl
	}
	return ""
}

func (x *GetCatAsyncResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Task struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TaskId             string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	PercentageComplete int32                  `protobuf:"varint,2,opt,name=percentage_complete,json=percentageComplete,proto3" json:"percentage_complete,omitempty"`
	Status             string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // PENDING, IN_PROGRESS, COMPLETED, FAILED
	Message            string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	ObjectReturned     *Cat                   `protobuf:"bytes,5,opt,name=object_returned,json=objectReturned,proto3" json:"object_returned,omitempty"` // The result when completed
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_cat_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_cat_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_cat_service_proto_rawDescGZIP(), []int{12}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetPercentageComplete() int32 {
	if x != nil {
		return x.PercentageComplete
	}
	return 0
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Task) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Task) GetObjectReturned() *Cat {
	if x != nil {
		return x.ObjectReturned
	}
	return nil
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_cat_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_cat_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_cat_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cat_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_cat_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_cat_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_cat_service_proto_rawDescGZIP(), []int{15}
}

func (x *CreateTaskRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_cat_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cat_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_cat_service_proto_rawDescGZIP(), []int{16}
}

func (x *CreateTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type UpdateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Task          *Task                  `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_cat_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_cat_service_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UpdateTaskRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type UpdateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskResponse) Reset() {
	*x = UpdateTaskResponse{}
	mi := &file_cat_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskResponse) ProtoMessage() {}

func (x *UpdateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cat_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskResponse) Descriptor() ([]byte, []int) {
	return file_cat_service_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

var File_cat_service_proto protoreflect.FileDescriptor

const file_cat_service_proto_rawDesc = "" +
	"\n" +
	"\x11cat_service.proto\x12\x0emock.v4.config\x1a\fconfig.proto\"m\n" +
	"\x0fListCatsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x18\n" +
	"\aorderby\x18\x04 \x01(\tR\aorderby\"\x86\x01\n" +
	"\x10ListCatsResponse\x12'\n" +
	"\x04cats\x18\x01 \x03(\v2\x13.mock.v4.config.CatR\x04cats\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"&\n" +
	"\rGetCatRequest\x12\x15\n" +
	"\x06cat_id\x18\x01 \x01(\x05R\x05catId\"7\n" +
	"\x0eGetCatResponse\x12%\n" +
	"\x03cat\x18\x01 \x01(\v2\x13.mock.v4.config.CatR\x03cat\"9\n" +
	"\x10CreateCatRequest\x12%\n" +
	"\x03cat\x18\x01 \x01(\v2\x13.mock.v4.config.CatR\x03cat\":\n" +
	"\x11CreateCatResponse\x12%\n" +
	"\x03cat\x18\x01 \x01(\v2\x13.mock.v4.config.CatR\x03cat\"P\n" +
	"\x10UpdateCatRequest\x12\x15\n" +
	"\x06cat_id\x18\x01 \x01(\x05R\x05catId\x12%\n" +
	"\x03cat\x18\x02 \x01(\v2\x13.mock.v4.config.CatR\x03cat\":\n" +
	"\x11UpdateCatResponse\x12%\n" +
	"\x03cat\x18\x01 \x01(\v2\x13.mock.v4.config.CatR\x03cat\")\n" +
	"\x10DeleteCatRequest\x12\x15\n" +
	"\x06cat_id\x18\x01 \x01(\x05R\x05catId\"G\n" +
	"\x11DeleteCatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"+\n" +
	"\x12GetCatAsyncRequest\x12\x15\n" +
	"\x06cat_id\x18\x01 \x01(\x05R\x05catId\"c\n" +
	"\x13GetCatAsyncResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\bpoll_url\x18\x02 \x01(\tR\apollUrl\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xc0\x01\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12/\n" +
	"\x13percentage_complete\x18\x02 \x01(\x05R\x12percentageComplete\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12<\n" +
	"\x0fobject_returned\x18\x05 \x01(\v2\x13.mock.v4.config.CatR\x0eobjectReturned\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\";\n" +
	"\x0fGetTaskResponse\x12(\n" +
	"\x04task\x18\x01 \x01(\v2\x14.mock.v4.config.TaskR\x04task\"=\n" +
	"\x11CreateTaskRequest\x12(\n" +
	"\x04task\x18\x01 \x01(\v2\x14.mock.v4.config.TaskR\x04task\">\n" +
	"\x12CreateTaskResponse\x12(\n" +
	"\x04task\x18\x01 \x01(\v2\x14.mock.v4.config.TaskR\x04task\"V\n" +
	"\x11UpdateTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12(\n" +
	"\x04task\x18\x02 \x01(\v2\x14.mock.v4.config.TaskR\x04task\">\n" +
	"\x12UpdateTaskResponse\x12(\n" +
	"\x04task\x18\x01 \x01(\v2\x14.mock.v4.config.TaskR\x04task2\xf2\x03\n" +
	"\n" +
	"CatService\x12M\n" +
	"\bListCats\x12\x1f.mock.v4.config.ListCatsRequest\x1a .mock.v4.config.ListCatsResponse\x12G\n" +
	"\x06GetCat\x12\x1d.mock.v4.config.GetCatRequest\x1a\x1e.mock.v4.config.GetCatResponse\x12P\n" +
	"\tCreateCat\x12 .mock.v4.config.CreateCatRequest\x1a!.mock.v4.config.CreateCatResponse\x12P\n" +
	"\tUpdateCat\x12 .mock.v4.config.UpdateCatRequest\x1a!.mock.v4.config.UpdateCatResponse\x12P\n" +
	"\tDeleteCat\x12 .mock.v4.config.DeleteCatRequest\x1a!.mock.v4.config.DeleteCatResponse\x12V\n" +
	"\vGetCatAsync\x12\".mock.v4.config.GetCatAsyncRequest\x1a#.mock.v4.config.GetCatAsyncResponse2\x83\x02\n" +
	"\vTaskService\x12S\n" +
	"\n" +
	"CreateTask\x12!.mock.v4.config.CreateTaskRequest\x1a\".mock.v4.config.CreateTaskResponse\x12J\n" +
	"\aGetTask\x12\x1e.mock.v4.config.GetTaskRequest\x1a\x1f.mock.v4.config.GetTaskResponse\x12S\n" +
	"\n" +
	"UpdateTask\x12!.mock.v4.config.UpdateTaskRequest\x1a\".mock.v4.config.UpdateTaskResponseBx\n" +
	"\x1acom.nutanix.mock.v4.configP\x01ZXgithub.com/nutanix/ntnx-api-golang-mock-pc/generated-code/protobuf/mock/v4/config;configb\x06proto3"

var (
	file_cat_service_proto_rawDescOnce sync.Once
	file_cat_service_proto_rawDescData []byte
)

func file_cat_service_proto_rawDescGZIP() []byte {
	file_cat_service_proto_rawDescOnce.Do(func() {
		file_cat_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cat_service_proto_rawDesc), len(file_cat_service_proto_rawDesc)))
	})
	return file_cat_service_proto_rawDescData
}

var file_cat_service_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_cat_service_proto_goTypes = []any{
	(*ListCatsRequest)(nil),     // 0: mock.v4.config.ListCatsRequest
	(*ListCatsResponse)(nil),    // 1: mock.v4.config.ListCatsResponse
	(*GetCatRequest)(nil),       // 2: mock.v4.config.GetCatRequest
	(*GetCatResponse)(nil),      // 3: mock.v4.config.GetCatResponse
	(*CreateCatRequest)(nil),    // 4: mock.v4.config.CreateCatRequest
	(*CreateCatResponse)(nil),   // 5: mock.v4.config.CreateCatResponse
	(*UpdateCatRequest)(nil),    // 6: mock.v4.config.UpdateCatRequest
	(*UpdateCatResponse)(nil),   // 7: mock.v4.config.UpdateCatResponse
	(*DeleteCatRequest)(nil),    // 8: mock.v4.config.DeleteCatRequest
	(*DeleteCatResponse)(nil),   // 9: mock.v4.config.DeleteCatResponse
	(*GetCatAsyncRequest)(nil),  // 10: mock.v4.config.GetCatAsyncRequest
	(*GetCatAsyncResponse)(nil), // 11: mock.v4.config.GetCatAsyncResponse
	(*Task)(nil),                // 12: mock.v4.config.Task
	(*GetTaskRequest)(nil),      // 13: mock.v4.config.GetTaskRequest
	(*GetTaskResponse)(nil),     // 14: mock.v4.config.GetTaskResponse
	(*CreateTaskRequest)(nil),   // 15: mock.v4.config.CreateTaskRequest
	(*CreateTaskResponse)(nil),  // 16: mock.v4.config.CreateTaskResponse
	(*UpdateTaskRequest)(nil),   // 17: mock.v4.config.UpdateTaskRequest
	(*UpdateTaskResponse)(nil),  // 18: mock.v4.config.UpdateTaskResponse
	(*Cat)(nil),                 // 19: mock.v4.config.Cat
}
var file_cat_service_proto_depIdxs = []int32{
	19, // 0: mock.v4.config.ListCatsResponse.cats:type_name -> mock.v4.config.Cat
	19, // 1: mock.v4.config.GetCatResponse.cat:type_name -> mock.v4.config.Cat
	19, // 2: mock.v4.config.CreateCatRequest.cat:type_name -> mock.v4.config.Cat
	19, // 3: mock.v4.config.CreateCatResponse.cat:type_name -> mock.v4.config.Cat
	19, // 4: mock.v4.config.UpdateCatRequest.cat:type_name -> mock.v4.config.Cat
	19, // 5: mock.v4.config.UpdateCatResponse.cat:type_name -> mock.v4.config.Cat
	19, // 6: mock.v4.config.Task.object_returned:type_name -> mock.v4.config.Cat
	12, // 7: mock.v4.config.GetTaskResponse.task:type_name -> mock.v4.config.Task
	12, // 8: mock.v4.config.CreateTaskRequest.task:type_name -> mock.v4.config.Task
	12, // 9: mock.v4.config.CreateTaskResponse.task:type_name -> mock.v4.config.Task
	12, // 10: mock.v4.config.UpdateTaskRequest.task:type_name -> mock.v4.config.Task
	12, // 11: mock.v4.config.UpdateTaskResponse.task:type_name -> mock.v4.config.Task
	0,  // 12: mock.v4.config.CatService.ListCats:input_type -> mock.v4.config.ListCatsRequest
	2,  // 13: mock.v4.config.CatService.GetCat:input_type -> mock.v4.config.GetCatRequest
	4,  // 14: mock.v4.config.CatService.CreateCat:input_type -> mock.v4.config.CreateCatRequest
	6,  // 15: mock.v4.config.CatService.UpdateCat:input_type -> mock.v4.config.UpdateCatRequest
	8,  // 16: mock.v4.config.CatService.DeleteCat:input_type -> mock.v4.config.DeleteCatRequest
	10, // 17: mock.v4.config.CatService.GetCatAsync:input_type -> mock.v4.config.GetCatAsyncRequest
	15, // 18: mock.v4.config.TaskService.CreateTask:input_type -> mock.v4.config.CreateTaskRequest
	13, // 19: mock.v4.config.TaskService.GetTask:input_type -> mock.v4.config.GetTaskRequest
	17, // 20: mock.v4.config.TaskService.UpdateTask:input_type -> mock.v4.config.UpdateTaskRequest
	1,  // 21: mock.v4.config.CatService.ListCats:output_type -> mock.v4.config.ListCatsResponse
	3,  // 22: mock.v4.config.CatService.GetCat:output_type -> mock.v4.config.GetCatResponse
	5,  // 23: mock.v4.config.CatService.CreateCat:output_type -> mock.v4.config.CreateCatResponse
	7,  // 24: mock.v4.config.CatService.UpdateCat:output_type -> mock.v4.config.UpdateCatResponse
	9,  // 25: mock.v4.config.CatService.DeleteCat:output_type -> mock.v4.config.DeleteCatResponse
	11, // 26: mock.v4.config.CatService.GetCatAsync:output_type -> mock.v4.config.GetCatAsyncResponse
	16, // 27: mock.v4.config.TaskService.CreateTask:output_type -> mock.v4.config.CreateTaskResponse
	14, // 28: mock.v4.config.TaskService.GetTask:output_type -> mock.v4.config.GetTaskResponse
	18, // 29: mock.v4.config.TaskService.UpdateTask:output_type -> mock.v4.config.UpdateTaskResponse
	21, // [21:30] is the sub-list for method output_type
	12, // [12:21] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_cat_service_proto_init() }
func file_cat_service_proto_init() {
	if File_cat_service_proto != nil {
		return
	}
	file_config_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cat_service_proto_rawDesc), len(file_cat_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_cat_service_proto_goTypes,
		DependencyIndexes: file_cat_service_proto_depIdxs,
		MessageInfos:      file_cat_service_proto_msgTypes,
	}.Build()
	File_cat_service_proto = out.File
	file_cat_service_proto_goTypes = nil
	file_cat_service_proto_depIdxs = nil
}
