//
// Generated file mock/v4/config/config.proto.
//
// Product version: 1.0.0-SNAPSHOT
//
// Part of the GoLang Mock API - REST API for Mock Cat Service
//
// (c) 2025 Nutanix Inc.  All rights reserved
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: config.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Map wrapper message
type ObjectMapWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value field in wrapper message
	Value         map[string]*anypb.Any `protobuf:"bytes,1000,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectMapWrapper) Reset() {
	*x = ObjectMapWrapper{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectMapWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectMapWrapper) ProtoMessage() {}

func (x *ObjectMapWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectMapWrapper.ProtoReflect.Descriptor instead.
func (*ObjectMapWrapper) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectMapWrapper) GetValue() map[string]*anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

// Cat entity for mock REST API
type Cat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the cat
	CatId int32 `protobuf:"varint,1,opt,name=cat_id,json=catId,proto3" json:"cat_id,omitempty"`
	// Name of the cat
	CatName string `protobuf:"bytes,2,opt,name=cat_name,json=catName,proto3" json:"cat_name,omitempty"`
	// Type of cat
	CatType string `protobuf:"bytes,3,opt,name=cat_type,json=catType,proto3" json:"cat_type,omitempty"`
	// Description of the cat
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Path to cat image file
	CatImageFile string `protobuf:"bytes,5,opt,name=cat_image_file,json=catImageFile,proto3" json:"cat_image_file,omitempty"`
	// Location information
	Location *Location `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	// Reserved fields
	XReserved     *ObjectMapWrapper `protobuf:"bytes,7,opt,name=_reserved,json=Reserved,proto3" json:"_reserved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cat) Reset() {
	*x = Cat{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cat) ProtoMessage() {}

func (x *Cat) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cat.ProtoReflect.Descriptor instead.
func (*Cat) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *Cat) GetCatId() int32 {
	if x != nil {
		return x.CatId
	}
	return 0
}

func (x *Cat) GetCatName() string {
	if x != nil {
		return x.CatName
	}
	return ""
}

func (x *Cat) GetCatType() string {
	if x != nil {
		return x.CatType
	}
	return ""
}

func (x *Cat) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Cat) GetCatImageFile() string {
	if x != nil {
		return x.CatImageFile
	}
	return ""
}

func (x *Cat) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Cat) GetXReserved() *ObjectMapWrapper {
	if x != nil {
		return x.XReserved
	}
	return nil
}

// Country information
type Country struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// State or province name
	State string `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	// Reserved fields
	XReserved     *ObjectMapWrapper `protobuf:"bytes,2,opt,name=_reserved,json=Reserved,proto3" json:"_reserved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Country) Reset() {
	*x = Country{}
	mi := &file_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Country) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Country) ProtoMessage() {}

func (x *Country) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Country.ProtoReflect.Descriptor instead.
func (*Country) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

func (x *Country) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Country) GetXReserved() *ObjectMapWrapper {
	if x != nil {
		return x.XReserved
	}
	return nil
}

// Geographical location information
type Location struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Country information
	Country *Country `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	// City name
	City string `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	// ZIP or postal code
	Zip string `protobuf:"bytes,3,opt,name=zip,proto3" json:"zip,omitempty"`
	// Reserved fields
	XReserved     *ObjectMapWrapper `protobuf:"bytes,4,opt,name=_reserved,json=Reserved,proto3" json:"_reserved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3}
}

func (x *Location) GetCountry() *Country {
	if x != nil {
		return x.Country
	}
	return nil
}

func (x *Location) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Location) GetZip() string {
	if x != nil {
		return x.Zip
	}
	return ""
}

func (x *Location) GetXReserved() *ObjectMapWrapper {
	if x != nil {
		return x.XReserved
	}
	return nil
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\x0emock.v4.config\x1a\x19google/protobuf/any.proto\"\xa6\x01\n" +
	"\x10ObjectMapWrapper\x12B\n" +
	"\x05value\x18\xe8\a \x03(\v2+.mock.v4.config.ObjectMapWrapper.ValueEntryR\x05value\x1aN\n" +
	"\n" +
	"ValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\"\x8f\x02\n" +
	"\x03Cat\x12\x15\n" +
	"\x06cat_id\x18\x01 \x01(\x05R\x05catId\x12\x19\n" +
	"\bcat_name\x18\x02 \x01(\tR\acatName\x12\x19\n" +
	"\bcat_type\x18\x03 \x01(\tR\acatType\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12$\n" +
	"\x0ecat_image_file\x18\x05 \x01(\tR\fcatImageFile\x124\n" +
	"\blocation\x18\x06 \x01(\v2\x18.mock.v4.config.LocationR\blocation\x12=\n" +
	"\t_reserved\x18\a \x01(\v2 .mock.v4.config.ObjectMapWrapperR\bReserved\"^\n" +
	"\aCountry\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12=\n" +
	"\t_reserved\x18\x02 \x01(\v2 .mock.v4.config.ObjectMapWrapperR\bReserved\"\xa2\x01\n" +
	"\bLocation\x121\n" +
	"\acountry\x18\x01 \x01(\v2\x17.mock.v4.config.CountryR\acountry\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x10\n" +
	"\x03zip\x18\x03 \x01(\tR\x03zip\x12=\n" +
	"\t_reserved\x18\x04 \x01(\v2 .mock.v4.config.ObjectMapWrapperR\bReservedBx\n" +
	"\x1acom.nutanix.mock.v4.configP\x01ZXgithub.com/nutanix/ntnx-api-golang-mock-pc/generated-code/protobuf/mock/v4/config;configb\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_config_proto_goTypes = []any{
	(*ObjectMapWrapper)(nil), // 0: mock.v4.config.ObjectMapWrapper
	(*Cat)(nil),              // 1: mock.v4.config.Cat
	(*Country)(nil),          // 2: mock.v4.config.Country
	(*Location)(nil),         // 3: mock.v4.config.Location
	nil,                      // 4: mock.v4.config.ObjectMapWrapper.ValueEntry
	(*anypb.Any)(nil),        // 5: google.protobuf.Any
}
var file_config_proto_depIdxs = []int32{
	4, // 0: mock.v4.config.ObjectMapWrapper.value:type_name -> mock.v4.config.ObjectMapWrapper.ValueEntry
	3, // 1: mock.v4.config.Cat.location:type_name -> mock.v4.config.Location
	0, // 2: mock.v4.config.Cat._reserved:type_name -> mock.v4.config.ObjectMapWrapper
	0, // 3: mock.v4.config.Country._reserved:type_name -> mock.v4.config.ObjectMapWrapper
	2, // 4: mock.v4.config.Location.country:type_name -> mock.v4.config.Country
	0, // 5: mock.v4.config.Location._reserved:type_name -> mock.v4.config.ObjectMapWrapper
	5, // 6: mock.v4.config.ObjectMapWrapper.ValueEntry.value:type_name -> google.protobuf.Any
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
