//
// Generated file mock/v4/config/config.proto.
//
// Product version: 1.0.0-SNAPSHOT
//
// Part of the GoLang Mock API - REST API for Mock Cat Service
//
// (c) 2025 Nutanix Inc.  All rights reserved
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: swagger/mock/v4/config/config.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Map wrapper message
type ObjectMapWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Value field in wrapper message
	Value         map[string]*anypb.Any `protobuf:"bytes,1000,rep,name=value" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectMapWrapper) Reset() {
	*x = ObjectMapWrapper{}
	mi := &file_swagger_mock_v4_config_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectMapWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectMapWrapper) ProtoMessage() {}

func (x *ObjectMapWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_swagger_mock_v4_config_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectMapWrapper.ProtoReflect.Descriptor instead.
func (*ObjectMapWrapper) Descriptor() ([]byte, []int) {
	return file_swagger_mock_v4_config_config_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectMapWrapper) GetValue() map[string]*anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

// Cat entity for mock REST API
type Cat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the cat
	CatId *int32 `protobuf:"varint,2001,opt,name=cat_id,json=catId" json:"cat_id,omitempty"`
	// Name of the cat
	CatName *string `protobuf:"bytes,2002,opt,name=cat_name,json=catName" json:"cat_name,omitempty"`
	// Type of cat
	CatType *string `protobuf:"bytes,2003,opt,name=cat_type,json=catType" json:"cat_type,omitempty"`
	// Description of the cat
	Description *string `protobuf:"bytes,2004,opt,name=description" json:"description,omitempty"`
	// Path to cat image file
	CatImageFile *string `protobuf:"bytes,2005,opt,name=cat_image_file,json=catImageFile" json:"cat_image_file,omitempty"`
	Location *Location `protobuf:"bytes,2006,opt,name=location" json:"location,omitempty"`
	XReserved     *ObjectMapWrapper `protobuf:"bytes,900000,opt,name=_reserved,json=Reserved" json:"_reserved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cat) Reset() {
	*x = Cat{}
	mi := &file_swagger_mock_v4_config_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cat) ProtoMessage() {}

func (x *Cat) ProtoReflect() protoreflect.Message {
	mi := &file_swagger_mock_v4_config_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cat.ProtoReflect.Descriptor instead.
func (*Cat) Descriptor() ([]byte, []int) {
	return file_swagger_mock_v4_config_config_proto_rawDescGZIP(), []int{1}
}

func (x *Cat) GetCatId() int32 {
	if x != nil && x.CatId != nil {
		return *x.CatId
	}
	return 0
}

func (x *Cat) GetCatName() string {
	if x != nil && x.CatName != nil {
		return *x.CatName
	}
	return ""
}

func (x *Cat) GetCatType() string {
	if x != nil && x.CatType != nil {
		return *x.CatType
	}
	return ""
}

func (x *Cat) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Cat) GetCatImageFile() string {
	if x != nil && x.CatImageFile != nil {
		return *x.CatImageFile
	}
	return ""
}

func (x *Cat) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Cat) GetXReserved() *ObjectMapWrapper {
	if x != nil {
		return x.XReserved
	}
	return nil
}

// Country information
type Country struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// State or province name
	State *string `protobuf:"bytes,2001,opt,name=state" json:"state,omitempty"`
	XReserved     *ObjectMapWrapper `protobuf:"bytes,900000,opt,name=_reserved,json=Reserved" json:"_reserved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Country) Reset() {
	*x = Country{}
	mi := &file_swagger_mock_v4_config_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Country) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Country) ProtoMessage() {}

func (x *Country) ProtoReflect() protoreflect.Message {
	mi := &file_swagger_mock_v4_config_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Country.ProtoReflect.Descriptor instead.
func (*Country) Descriptor() ([]byte, []int) {
	return file_swagger_mock_v4_config_config_proto_rawDescGZIP(), []int{2}
}

func (x *Country) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *Country) GetXReserved() *ObjectMapWrapper {
	if x != nil {
		return x.XReserved
	}
	return nil
}

// Geographical location information
type Location struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Country *Country `protobuf:"bytes,2001,opt,name=country" json:"country,omitempty"`
	// City name
	City *string `protobuf:"bytes,2002,opt,name=city" json:"city,omitempty"`
	// ZIP or postal code
	Zip *string `protobuf:"bytes,2003,opt,name=zip" json:"zip,omitempty"`
	XReserved     *ObjectMapWrapper `protobuf:"bytes,900000,opt,name=_reserved,json=Reserved" json:"_reserved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_swagger_mock_v4_config_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_swagger_mock_v4_config_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_swagger_mock_v4_config_config_proto_rawDescGZIP(), []int{3}
}

func (x *Location) GetCountry() *Country {
	if x != nil {
		return x.Country
	}
	return nil
}

func (x *Location) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *Location) GetZip() string {
	if x != nil && x.Zip != nil {
		return *x.Zip
	}
	return ""
}

func (x *Location) GetXReserved() *ObjectMapWrapper {
	if x != nil {
		return x.XReserved
	}
	return nil
}

var File_swagger_mock_v4_config_config_proto protoreflect.FileDescriptor

const file_swagger_mock_v4_config_config_proto_rawDesc = "" +
	"\n" +
	"#swagger/mock/v4/config/config.proto\x12\x0emock.v4.config\x1a\x19google/protobuf/any.proto\"\xa6\x01\n" +
	"\x10ObjectMapWrapper\x12B\n" +
	"\x05value\x18\xe8\a \x03(\v2+.mock.v4.config.ObjectMapWrapper.ValueEntryR\x05value\x1aN\n" +
	"\n" +
	"ValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\"\x97\x02\n" +
	"\x03Cat\x12\x16\n" +
	"\x06cat_id\x18\xd1\x0f \x01(\x05R\x05catId\x12\x1a\n" +
	"\bcat_name\x18\xd2\x0f \x01(\tR\acatName\x12\x1a\n" +
	"\bcat_type\x18\xd3\x0f \x01(\tR\acatType\x12!\n" +
	"\vdescription\x18\xd4\x0f \x01(\tR\vdescription\x12%\n" +
	"\x0ecat_image_file\x18\xd5\x0f \x01(\tR\fcatImageFile\x125\n" +
	"\blocation\x18\xd6\x0f \x01(\v2\x18.mock.v4.config.LocationR\blocation\x12?\n" +
	"\t_reserved\x18\xa0\xf76 \x01(\v2 .mock.v4.config.ObjectMapWrapperR\bReserved\"a\n" +
	"\aCountry\x12\x15\n" +
	"\x05state\x18\xd1\x0f \x01(\tR\x05state\x12?\n" +
	"\t_reserved\x18\xa0\xf76 \x01(\v2 .mock.v4.config.ObjectMapWrapperR\bReserved\"\xa7\x01\n" +
	"\bLocation\x122\n" +
	"\acountry\x18\xd1\x0f \x01(\v2\x17.mock.v4.config.CountryR\acountry\x12\x13\n" +
	"\x04city\x18\xd2\x0f \x01(\tR\x04city\x12\x11\n" +
	"\x03zip\x18\xd3\x0f \x01(\tR\x03zip\x12?\n" +
	"\t_reserved\x18\xa0\xf76 \x01(\v2 .mock.v4.config.ObjectMapWrapperR\bReservedB\"\n" +
	"\x0emock.v4.configP\x01Z\x0emock/v4/config"

var (
	file_swagger_mock_v4_config_config_proto_rawDescOnce sync.Once
	file_swagger_mock_v4_config_config_proto_rawDescData []byte
)

func file_swagger_mock_v4_config_config_proto_rawDescGZIP() []byte {
	file_swagger_mock_v4_config_config_proto_rawDescOnce.Do(func() {
		file_swagger_mock_v4_config_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_swagger_mock_v4_config_config_proto_rawDesc), len(file_swagger_mock_v4_config_config_proto_rawDesc)))
	})
	return file_swagger_mock_v4_config_config_proto_rawDescData
}

var file_swagger_mock_v4_config_config_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_swagger_mock_v4_config_config_proto_goTypes = []any{
	(*ObjectMapWrapper)(nil), // 0: mock.v4.config.ObjectMapWrapper
	(*Cat)(nil),              // 1: mock.v4.config.Cat
	(*Country)(nil),          // 2: mock.v4.config.Country
	(*Location)(nil),         // 3: mock.v4.config.Location
	nil,                      // 4: mock.v4.config.ObjectMapWrapper.ValueEntry
	(*anypb.Any)(nil),        // 5: google.protobuf.Any
}
var file_swagger_mock_v4_config_config_proto_depIdxs = []int32{
	4, // 0: mock.v4.config.ObjectMapWrapper.value:type_name -> mock.v4.config.ObjectMapWrapper.ValueEntry
	3, // 1: mock.v4.config.Cat.location:type_name -> mock.v4.config.Location
	0, // 2: mock.v4.config.Cat._reserved:type_name -> mock.v4.config.ObjectMapWrapper
	0, // 3: mock.v4.config.Country._reserved:type_name -> mock.v4.config.ObjectMapWrapper
	2, // 4: mock.v4.config.Location.country:type_name -> mock.v4.config.Country
	0, // 5: mock.v4.config.Location._reserved:type_name -> mock.v4.config.ObjectMapWrapper
	5, // 6: mock.v4.config.ObjectMapWrapper.ValueEntry.value:type_name -> google.protobuf.Any
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_swagger_mock_v4_config_config_proto_init() }
func file_swagger_mock_v4_config_config_proto_init() {
	if File_swagger_mock_v4_config_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_swagger_mock_v4_config_config_proto_rawDesc), len(file_swagger_mock_v4_config_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_swagger_mock_v4_config_config_proto_goTypes,
		DependencyIndexes: file_swagger_mock_v4_config_config_proto_depIdxs,
		MessageInfos:      file_swagger_mock_v4_config_config_proto_msgTypes,
	}.Build()
	File_swagger_mock_v4_config_config_proto = out.File
	file_swagger_mock_v4_config_config_proto_goTypes = nil
	file_swagger_mock_v4_config_config_proto_depIdxs = nil
}
